{
 "title": "WINDOWS-DETECT-RDP-SESSIONS-COPILOT-ACTION",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "agent_name",
    "label": "Agent",
    "query": "{ \"find\": \"terms\", \"field\": \"agent_name\", \"query\": \"\"}"
   },
   {
    "name": "rule_level",
    "label": "Rule Level",
    "query": "{ \"find\": \"terms\", \"field\": \"rule_level\", \"query\": \"\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "EVENTS (TOTAL)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:331",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:329", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND data_action:detect_rdp_sessions AND data_copilot_action:true",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTS BY AGENT",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "agent_name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_action:detect_rdp_sessions AND data_copilot_action:true",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTS - DETAILS",
   "type": "logs",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "settings": { "limit": "250" }, "type": "logs" }
     ],
     "query": "data_action:detect_rdp_sessions AND data_copilot_action:true",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MAX SEVERITY (0 - 15)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rule_level",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "agent_name:$agent_name AND data_action:detect_rdp_sessions AND data_copilot_action:true",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTS BY CATEGORY",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "data_user",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "data_action:detect_rdp_sessions AND data_copilot_action:true",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AGENTS",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:235",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:233",
       "field": "agent_name",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "agent_name:$agent_name AND data_action:detect_rdp_sessions AND data_copilot_action:true",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "TOP 10 AGENTS - HISTOGRAM",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent_name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent_name:$agent_name AND data_action:List-Listening-Ports AND data_copilot_action:true",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "250" }, "type": "raw_data" }
     ],
     "query": "agent_name:$agent_name AND data_action:detect_rdp_sessions AND data_copilot_action:true",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}